### ISSUE TITLE
Install error with PHP before 7

### ISSUE THREAD

**Issue by mnakalay** [ortic/concrete5-forum#18]
I get this during install:
"Default value for parameters with a class type hint can only be NULL". PHP version is 5.6.25 and the install doesn't run.

Installed correctly under PHP 7.0.11

**Comment by MichaelMaar** [comment]
I have seen something like this. There is an issue where in functions (example):

public function sortByLastActivityDate(string $dir = 'asc')

if I loose the "string" parameter it works (example):

public function sortByLastActivityDate($dir = 'asc')

In the first versions of ortic forum there was a lot of these, but in the latest version I have only been able to find one in /packages/ortic_forum/src/ForumTopicList.php in the above described function.

**Comment by Remo** [comment]
the repo class has lots of them. I don't think i will remove them, i will probably add even more. php 5.6 is almost end of life. maybe i will use a script to remove them in a build release, but that's low prio

**Comment by Remo** [comment]
If anyone is unable to update to a proper PHP version I'd recommend giving this a try https://github.com/jaytaph/Transphpile
It's not something I'll put on my todo list

**Comment by mnakalay** [comment]
@Remo, I agree you shouldn't even worry about this. My point (which I forgot to make) was that you should just add the requirements in the Readme.

**Comment by Remo** [comment]
already added ;-)
thanks
