### ISSUE TITLE
Add subject tags

### ISSUE THREAD

**Issue by hemiipatu** [ortic/concrete5-forum#21]
I think it would be quite useful _(Especially when forums grow)_ to include some form of subject tagging which users can either select from a predefined list or manually enter on each post? 

Because it's also subjective to opinion on what the post is related to, it should also be something which an admin user can change if needed.

**Comment by Remo** [comment]
I have some doubts about a predefined list, it will never contain the tags the user is looking for, in the end people are simply not going to select it, maybe a list that can be extended like we have on concrete5.org.

However, the only forum I can think of that has this feature is the one on concrete5.org, not even really big forums like reddit have it. Personally I believe a good subject is enough, addings tags is hard and to be honest, I don't even know what happens with the tags on concrete5.org. Is there a word cloud where you can see the most active tags or something? Just seeing some tags below the subject isn't adding any kind of value to me, but maybe others have a different opinion.

I'm not oposed to have that feature in this package if it could be disabled, but I certainly don't see enough need to work on this myself. If someone needs this and sends a pull requests I would review and merge it though.

**Comment by hemiipatu** [comment]
Hmm I don't know if tags are the correct word, so I've tried to explain it below? 

A lot of forums, including Reddit have some form of subject based separation, tagging or ordering. ie. Reddit has SubReddits which determines the subject users might post. A number of other forums I've seen also follow a similar system whereas they separate the topic for easier grouping to ensure users can more easily find and access valid information or topics they're after?

Let's say you are an app developer and you run a site, you might want forums to build a community and leverage community help. So the dev might separate things by making:

Help
    > All the posts 

Bugs
    > All the posts 

Requests 
    > All the posts

I hope this better conveys what I was thinking.

**Comment by Remo** [comment]
if you want forum categories you just create several forum pages, that way you can easily create "subreddits"

**Comment by hemiipatu** [comment]
I see, that makes perfect sense.
