### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by hemiipatu** [ortic/concrete5-forum#4]
Hi there, I recently saw that you are working on this sweet plugin/addon for concrete5. Is this safe to use in a production environment so that I can see the progress of it with my eyes as well as submit any potential errors/bugs as you progress? 

I would love to help with this project in that way.

**Comment by Remo** [comment]
if you check the issues you can see some basic features which are currently
missing. I don't think it makes sense to use it, but feel free to have a
look!

**Comment by hemiipatu** [comment]
Hi Remo, thanks for the reply. 

I'll certainly go ahead and use it, I'd not use it so that others outside the admin team can see it but I'll use it so that 20 of us can tinker and see how things go.

once a full release is available I'll also be more than happy to write up a "setup guide" to supplement your own if you've got one already. 🙊

**Comment by Remo** [comment]
I'm going to close this for now, as long as those issues I've created are open I wouldn't recommend to use it in production, but I'm always happy to get feedback (or even better pull requests).
