### ISSUE TITLE
PHP error if you post when not logged in

### ISSUE THREAD

**Issue by danielgwood** [ortic/concrete5-forum#9]
I have the forum package installed on an unprotected page at the moment while I test (and hopefully contribute!). There's nothing preventing me from viewing or posting as a "guest", which is fine, that probably needs to be a feature request.

However if you do post as a guest, you currently get: *Call to a member function getEntityObject() on null*.

This seems to be caused by `$topicPage` being null in the `Forum::writeTopic()` function.

Full error:
```
Error thrown with message "Call to a member function getEntityObject() on null"

Stacktrace:
#23 Error in .....\packages\ortic_forum\src\Repository\Forum.php:170
#22 Concrete\Package\OrticForum\Src\Repository\Forum:writeTopic in .....\packages\ortic_forum\controllers\page_types\Forum.php:33
#21 Concrete\Package\OrticForum\Controller\PageType\Forum:writeTopic in .....\concrete\src\Controller\AbstractController.php:294
#20 call_user_func_array in .....\concrete\src\Controller\AbstractController.php:294
#19 Concrete\Core\Controller\AbstractController:runAction in .....\concrete\src\Http\ResponseFactory.php:182
#18 Concrete\Core\Http\ResponseFactory:controller in .....\concrete\src\Http\ResponseFactory.php:369
#17 Concrete\Core\Http\ResponseFactory:collection in .....\concrete\src\Routing\DispatcherRouteCallback.php:34
#16 Concrete\Core\Routing\DispatcherRouteCallback:execute in .....\concrete\src\Http\DefaultDispatcher.php:122
#15 Concrete\Core\Http\DefaultDispatcher:handleDispatch in .....\concrete\src\Http\DefaultDispatcher.php:54
#14 Concrete\Core\Http\DefaultDispatcher:dispatch in .....\concrete\src\Http\Middleware\DispatcherDelegate.php:39
#13 Concrete\Core\Http\Middleware\DispatcherDelegate:next in .....\concrete\src\Http\Middleware\ThumbnailMiddleware.php:71
#12 Concrete\Core\Http\Middleware\ThumbnailMiddleware:process in .....\concrete\src\Http\Middleware\MiddlewareDelegate.php:38
#11 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in .....\concrete\src\Http\Middleware\FrameOptionsMiddleware.php:39
#10 Concrete\Core\Http\Middleware\FrameOptionsMiddleware:process in .....\concrete\src\Http\Middleware\MiddlewareDelegate.php:38
#9 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in .....\concrete\src\Http\Middleware\CookieMiddleware.php:37
#8 Concrete\Core\Http\Middleware\CookieMiddleware:process in .....\concrete\src\Http\Middleware\MiddlewareDelegate.php:38
#7 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in .....\concrete\src\Http\Middleware\ApplicationMiddleware.php:29
#6 Concrete\Core\Http\Middleware\ApplicationMiddleware:process in .....\concrete\src\Http\Middleware\MiddlewareDelegate.php:38
#5 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in .....\concrete\src\Http\Middleware\MiddlewareStack.php:86
#4 Concrete\Core\Http\Middleware\MiddlewareStack:process in .....\concrete\src\Http\DefaultServer.php:85
#3 Concrete\Core\Http\DefaultServer:handleRequest in .....\concrete\src\Foundation\Runtime\Run\DefaultRunner.php:115
#2 Concrete\Core\Foundation\Runtime\Run\DefaultRunner:run in .....\concrete\src\Foundation\Runtime\DefaultRuntime.php:102
#1 Concrete\Core\Foundation\Runtime\DefaultRuntime:run in .....\concrete\dispatcher.php:36
#0 require in .....\index.php:3
```

**Comment by danielgwood** [comment]
I guess my recommendation here would be to prevent people who aren't at least logged into the site from posting ever. That would be inviting spam from all kinds of bots anyway.

Secondary to that perhaps some basic permissions options. Allow picking a minimum user group for posting, maybe for viewing the forum (though one could achieve this with permissions on the Page itself).

**Comment by Remo** [comment]
yes I'm aware of this, it's unfortunately not a finished solution yet, but I'm working on it :wink:

**Comment by Remo** [comment]
Restricting guests from posting is certainly the way to go. I've just implemented this in the commit above.

I don't think I'll want to handle view permissions myself, why duplicate what concrete5 already does. I will consider adding a custom group to control writing permissions, but for now my focus is on finishing a basic and clean forum solution for concrete5.

**Comment by danielgwood** [comment]
Nice one, thanks!

Yeah 100% get the keeping it simple vibe. I may have to fork to meet some of the requirements I have (or it may get far more complicated than you want), but I'm hoping to still contribute back the majority of it.

**Comment by Remo** [comment]
What I'm certainly open to is events. If we can easily add some custom events that would make it possible to customize things, I'm all for it! Maybe it also makes sense to split the single pages into elements so that one can override a single element and maybe add a group check there. A simple, but extensible solution is what I aim at!
